### PR TITLE
Add shortcuts for running the program and deleting last statement

### PR DESCRIPTION
**Pull request by yanchith**

### CODE REVIEW

**Review by janper — COMMENTED** [review]
I'm not sure what this is  ¯\_(ツ)_/¯

**Review by janper — DISMISSED** [review]
I SEE!!! The name of this PR is just so unclear...

Great, it works really well! 

We should inform the user about this as well. What about this for now?
image

**Comment by yanchith** [comment]
> We should inform the user about this as well. What about this for now?

Sure. I'll add this

**Comment by yanchith** [comment]
> The name of this PR is just so unclear...

We have different internal and external terminology. I tend to use the internal one.

**Pull request merged**
