### PR TITLE
Add HS_FULLSCREEN option

### PR DESCRIPTION
**Pull request by yanchith**
Still left to do
- [x] test how the video mode iterator behaves on various systems and potentially implement more sophisticated selection
- [X] test on linux
- [x] test on windows (I'll do it later today)
- [ ] test on macOS (I'll do it tomorrow)
- [X] add workshop windows dist instructions

### CODE REVIEW

**Review by ondrowan — DISMISSED** [review]

**Comment by ondrowan** [comment]
It seemed to work fine on Windows.

**Comment by ondrowan** [comment]
MacOS is not OK though (but I'm gonna guess it's a low prio). Everything is tiny and FPS goes straight towards zero for me. Debug mode thought.

**Comment by yanchith** [comment]
> MacOS is not OK though (but I'm gonna guess it's a low prio). Everything is tiny and FPS goes straight towards zero for me. Debug mode thought.

Ok, I'll test on mine as well tomorrow. IIRC the FPS drop is a bug we already have reported, but the incorrect DPI might be new, and also might be related to selecting full-screen video mode.

**Review by janper — CHANGES_REQUESTED** [review]
Please, add Bash and Windows cmd instructions into the `readme.md`

**Review by janper — DISMISSED** [review]
thx

**Comment by yanchith** [comment]
> MacOS is not OK though (but I'm gonna guess it's a low prio). Everything is tiny and FPS goes straight towards zero for me. Debug mode thought.

Yep, confirmed. It did behave a bit better with borderless fullscreen, but not by much. Release build does not help. This bug was present before though (you could always fullscreen the app manually previously, so I would not block on this).

**Pull request merged**
